### ISSUE TITLE
Can't run production build

### ISSUE THREAD

**Issue by oscarni** [minichate/ember-cli-conditional-compile#19]
I'm trying to get this addon to work with v0.4.5.

I get `Uncaught ReferenceError: EMBER_CLI_CONDITIONAL_COMPILE_INJECTIONS is not defined` at runtime when I run in production. Everything works like expected in development.

I've read previous issues where this has been addressed, but it looks like it's here again. I'm running on ember-cli 1.13.14 and ember 2.3.0.

My ENV looks like this:

```js
var ENV = {
  // other settings ...
  featureFlags: {
    ENABLE_FEATURE: true
  },
  includeDirByFlag: {
    ENABLE_FEATURE: [/pods\/feature/]
}
```

Any ideas?

**Comment by minichate** [comment]
Interesting!

Do you have a small reproducible test case or application you can point me to?

**Comment by oscarni** [comment]
I can confirm that this issue is fixed in https://github.com/minichate/ember-cli-conditional-compile/releases/tag/release%2F0.4.6
Thanks!
