### ISSUE TITLE
camelCased flag doesn't create a helper.

### ISSUE THREAD

**Issue by GCheung55** [minichate/ember-cli-conditional-compile#27]
With a featureFlag in the config as `isFoo`, a `if-flag-isFoo` is missing.

**Comment by jobackman** [comment]
Care to elaborate some? I've been using camelcased featureFlags for a long time without any trouble.

 Are you getting errors or are the feature-flags not removing code like they should? If it's related to #21 try updating this addon to the lastest version and your ember-cli-htmlbars toa version that allows [cachebusting](https://github.com/ember-cli/ember-cli-htmlbars/pull/90).

**Comment by minichate** [comment]
@GCheung55 I can't repro this either; any chance you could submit a test case that shows the failing behaviour?

**Comment by GCheung55** [comment]
Yes. I'll put a test repo together.

**Comment by minichate** [comment]
@GCheung55 Any chance you've reproduced this? I can close this issue if not. Thanks!

**Comment by GCheung55** [comment]
I couldn't reproduce. Closing. Thanks!
