### ISSUE TITLE
How does this addon differ from https://github.com/jkarsrud/ember-cli-defeatureify?

### ISSUE THREAD

**Issue by notmessenger** [minichate/ember-cli-conditional-compile#45]
Is it just in syntax or have I missed functionality differences as well?

**Comment by minichate** [comment]
Hello! `defeaturify` doesn't do dead code elimination (to the best of my knowledge). In this add-on if features aren't enabled their code gets stripped out of the compiled build.

**Comment by minichate** [comment]
Additionally, it looks like `defeaturify` only supports predefined `ember-source` feature flags, whereas this supports user defined flags. Though I'm not 100% sure on this :)
