### ISSUE TITLE
Update to use with ember-cli-uglify@2.x

### ISSUE THREAD

**Issue by GCheung55** [minichate/ember-cli-conditional-compile#51]
I'm seeing the conditions failed to be removed by uglify@2.x.

**Comment by GCheung55** [comment]
Digging some, it looks like the reason is because `minifyJS` option has been dropped. Instead, it's the options are now under `uglify` property of the `ember-cli-uglify` options.

https://github.com/ember-cli/ember-cli-uglify/blob/master/index.js#L11-L35

**Comment by tehmaestro** [comment]
Hi, I tried applying your changes, but it sais `target.options['ember-cli-uglify']` is undefined

**Comment by Duder-onomy** [comment]
I think this is resolves in my fork of @GCheung55 good work. Can you both check it out in your apps?
