### ISSUE TITLE
Ember 2.x Compatibility Issues

### ISSUE THREAD

**Issue by andrewvy** [minichate/ember-cli-conditional-compile#9]
First off, thanks for this great addon, this is exactly what I've needed. :+1:

Right now the only breaking point is where we're dynamically creating handlebar helpers for template use. Since this way of registering helpers have been [deprecated/removed since 1.13.x](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_new-ember-js-helper-api)

`Uncaught TypeError: Ember.default.Handlebars.registerHelper is not a function`

Example: [src file](https://github.com/minichate/ember-cli-conditional-compile/blob/master/app/initializers/conditional-compile.js)

```handlebars
{{#if-flag-ENABLE_FOO}}
The FOO flag is enabled \o/
{{/if-flag-ENABLE_FOO}}
```

@minichate I'll try and looking into this more. From what I've seen so far, nobody has dynamically defined helpers before. :cry:

**Comment by minichate** [comment]
@andrewvy Thanks! I'll try and find some time to dig into the HTMLBars AST idea I mention to you on the other issue
